[project]
name = "ci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pon", email = "127575647+ponatca@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.64.0",
]

[project.scripts]
ci = "ci:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
